src/AppBundle/Entity/Movimiento.php
<?php

namespace AppBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 *
 * @ORM\Table(name="movimiento")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\MovimientoRepository")
 * 
*/
class Movimiento
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @ORM\ManyToOne(targetEntity="\AppBundle\Entity\Estado\Movimiento")
     * @ORM\JoinColumn(name="estado", referencedColumnName="id")
     */
    protected $estado;
    
    /**
     * @var \Date
     * 
     * @ORM\Column(name="fecha", type="date")
     *  
     */
    protected $fecha;
    
    /**
     * @ORM\ManyToOne(targetEntity="\AppBundle\Entity\Direccion")
     * @ORM\JoinColumn(name="direccion", referencedColumnName="id")
     */
    protected $direccion;
    
    /**
     * @ORM\Column(type="string")
     */
    protected $tipo;
    
    /**
     * @ORM\ManyToOne(targetEntity="Reserva", cascade={"remove"})
     * @ORM\JoinColumn(name="reserva", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $reserva;
        
    /**
     * @return Direccion
     */
    public function getDireccion(){
        return $this->direccion;
    }
    
    public function setFecha(\DateTime $fecha=null) {
        $this->fecha = $fecha;
        return $this;
    }

    public function setDireccion($direccion) {
        if($direccion instanceof Direccion){
            $this->direccion = (string)$direccion;
        }
        $this->direccion = $direccion;
        return $this;
    }

        /**
     * @return \DateTime
     */
    public function getFecha(){
        return $this->fecha;
    }
    
    public function __toString() {
        return "MOV ".$this->fecha->format("d-m-Y")." ".$this->direccion;
    }
    
    public function getId() {
        return $this->id;
    }
    
    /**
     * @return Estado\Movimiento
     */
    public function getEstado(){
        return $this->estado;
    }
    
    public function setEstado(Estado\Movimiento $estado){
        $this->estado = $estado;
        return $this;
    }
    
    /**
     * @return \AppBundle\Entity\Reserva
     */
    public function getReserva() {
        return $this->reserva;
    }

    public function setReserva(\AppBundle\Entity\Reserva $reserva = null) {
        if(!is_null($reserva)){
            $this->reserva = $reserva;
        }
        return $this;
    }

    public function getTipo() {
        return $this->tipo;
    }

    public function setTipo($tipo) {
        $this->tipo = $tipo;
        return $this;
    }

    public function getRestoDias(){
        $now = new \DateTime('now');
        $d = $now->diff($this->getFecha());
        if($d->format("%H") > 0 && $d->format("%r") != "-"){
            $r = $d->format("%r%a")+1;
        }else{
            $r = $d->format("%r%a");
        }
        return $r;
    }

    
}

src/AppBundle/Entity/Reserva.php
<?php

namespace AppBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use AppBundle\Model\Objeto;

/**
 *
 * @ORM\Table(name="reserva")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ReservaRepository")
 * @ORM\HasLifecycleCallbacks()
 *
 */
class Reserva
{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $fechaAlta;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $fechaUpdate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fechaInicio", type="datetime")
     */
    protected $fechaInicio;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fechaFin", type="datetime")
     */
    protected $fechaFin;

    /**
     *
     * @var String
     *
     * @ORM\Column(name="circuito", type="string")
     *
     */
    protected $circuito;

    /**
     *
     * @ORM\ManyToOne(targetEntity="Empresa")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="empresa", referencedColumnName="id")
     * })
     */
    protected $empresa;

    /**
     * @var Integer
     *
     * @ORM\Column(name="cantidad_receptores", type="integer")
     */
    protected $cantidadReceptores;

    /**
     * @var Integer
     *
     * @ORM\Column(name="cantidad_emisores", type="integer")
     */
    protected $cantidadEmisores;

    /**
     * @var Integer
     *
     * @ORM\Column(name="cantidad_reserva", type="integer")
     */
    protected $cantidadReserva = 2;

    /**
     * @var string
     *
     * @ORM\Column(name="modelo", type="string")
     */
    protected $modelo = "SAU";

    /**
     * @var Movimiento
     *
     * @ORM\ManyToOne(targetEntity="Movimiento", inversedBy="reserva", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="entrega", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $entrega;

    /**
     * @var Movimiento
     *
     * @ORM\ManyToOne(targetEntity="Movimiento", inversedBy="reserva",cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="recogida", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $recogida;

    /**
     * @var Estado\Reserva
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Estado\Reserva")
     * @ORM\JoinColumn(name="estado", referencedColumnName="id")
     */
    protected $estado;

    /**
     * @var float
     *
     * @ORM\Column(name="precio", type="float")
     */
    protected $precio = 1.8;

    /**
     * @var String
     *
     * @ORM\Column(name="precio_tipo", type="string")
     */
    protected $precioTipo = "simple";

    /**
     * @var float
     *
     * @ORM\Column(name="precio_impuestos", type="float")
     */
    protected $precioImpuestos = 21;

    /**
     * @var float
     *
     * @ORM\Column(name="precio_transporte", type="float")
     */
    protected $precioTransporte = 20;

    /**
     *
     * @ORM\Column(name="peticion", type="text",nullable=true)
     */
    protected $peticion;

    /**
     *
     * @ORM\Column(name="notas", type="text", nullable=true)
     */
    protected $notas;

    /**
     * @ORM\ManyToOne(targetEntity="Iweb\FactuBundle\Entity\Factura", inversedBy="pedido")
     * @ORM\JoinColumn(name="factura_id", referencedColumnName="id")
     */
    protected $factura;

    /**
     * @var Usuario
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="comercial", referencedColumnName="id")
     */
    protected $comercial;

    public function __construct()
    {
//        $this->estado = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     *
     * @return \Date
     */
    public function getFechaInicio()
    {
        return $this->fechaInicio;
    }

    /**
     *
     * @return \Date
     */
    public function getFechaFin()
    {
        return $this->fechaFin;
    }

    /**
     *
     * @return Integer
     */
    public function getCantidad()
    {
        return $this->cantidad;
    }

    /**
     *
     * @return Circuito
     */
    public function getCircuito()
    {
        return $this->circuito;
    }

//    public function addEntrega($movimiento)
//    {
//        $this->entrgega[] = $movimiento;
//        return $this;
//    }
//    public function addRecogida($movimiento)
//    {
//        $this->recogida[] = $movimiento;
//        return $this;
//    }
    /**
     *
     * @return Movimiento
     */
    public function getEntrega()
    {
        return $this->entrega;
    }

    /**
     *
     * @return Movimiento
     */
    public function getRecogida()
    {
        return $this->recogida;
    }

    public function __toString()
    {
        return "Reserva " . $this->getId();
    }

    public function setFechaInicio(\DateTime $fechaInicio)
    {
        $this->fechaInicio = $fechaInicio;
        return $this;
    }

    public function setFechaFin(\DateTime $fechaFin)
    {
        $this->fechaFin = $fechaFin;
        return $this;
    }

    public function setCircuito($circuito)
    {
        $this->circuito = $circuito;
        return $this;
    }

    public function setEmpresa(Empresa $empresa)
    {
        $this->empresa = $empresa;
        if ($empresa->getPrecioAlquiler() !== null) {
            $this->precio = $empresa->getPrecioAlquiler();
        }
        if ($empresa->getPrecioTipo() !== null) {
            $this->precioTipo = $empresa->getPrecioTipo();
        }
        if ($empresa->getPrecioTransporte() !== null) {
            $this->precioTransporte = $empresa->getPrecioTransporte();
        }
        return $this;
    }

    public function setCantidadReceptores($cantidadReceptores)
    {
        $this->cantidadReceptores = $cantidadReceptores;
        return $this;
    }

    public function setCantidadEmisores($cantidadEmisores)
    {
        $this->cantidadEmisores = $cantidadEmisores;
        return $this;
    }

    public function setCantidadReserva($cantidadReserva)
    {
        $this->cantidadReserva = $cantidadReserva;
        return $this;
    }

    public function setModelo($modelo)
    {
        $this->modelo = $modelo;
        return $this;
    }

    public function setEntrega(Movimiento $entrega)
    {
        $entrega->setReserva($this);
        $this->entrega = $entrega;
        return $this;
    }

    public function setRecogida(Movimiento $recogida)
    {
        $recogida->setReserva($this);
        $this->recogida = $recogida;
        return $this;
    }

    public function setPrecio($precio)
    {
        $this->precio = $precio;
        return $this;
    }

    public function setPrecioTipo($precioTipo)
    {
        $this->precioTipo = $precioTipo;
        return $this;
    }

    public function setPrecioImpuestos($precioImpuestos)
    {
        $this->precioImpuestos = $precioImpuestos;
        return $this;
    }

    public function setPrecioTransporte($precioTransporte)
    {
        $this->precioTransporte = $precioTransporte;
        return $this;
    }

    public function getEstado()
    {
        return $this->estado;
    }

    public function setEstado(Estado\Reserva $estado)
    {
        $this->estado = $estado;
        return $this;
    }

    public function getModelo()
    {
        return $this->modelo;
    }

    public function getPrecio()
    {
        return $this->precio;
    }

    public function getEmpresa()
    {
        return $this->empresa;
    }

    public function getCantidadReceptores()
    {
        return $this->cantidadReceptores;
    }

    public function getCantidadEmisores()
    {
        return $this->cantidadEmisores;
    }

    public function getCantidadReserva()
    {
        return $this->cantidadReserva;
    }

    public function getPrecioTipo()
    {
        return $this->precioTipo;
    }

    public function getPrecioImpuestos()
    {
        return $this->precioImpuestos;
    }

    public function getPrecioTransporte()
    {
        return $this->precioTransporte;
    }

    public function getEntregaFecha()
    {
        return $this->entregaFecha;
    }

    public function getEntregaDireccion()
    {
        return $this->entregaDireccion;
    }

    public function getEntregaEstado()
    {
        return $this->entregaEstado;
    }

    public function getRecogidaFecha()
    {
        return $this->recogidaFecha;
    }

    public function getRecogidaDias()
    {
        $now = new \DateTime('now');
        $d = $now->diff($this->getRecogidaFecha()); //->format("%r%d");
        if ($d->format("%H") > 0 && $d->format("%r") != "-") {
            $r = $d->format("%r%a") + 1;
        } else {
            $r = $d->format("%r%a");
        }
        return $r;
    }

    public function getRecogidaDireccion()
    {
        return $this->recogidaDireccion;
    }

    public function getRecogidaEstado()
    {
        return $this->recogidaEstado;
    }

    public function setEntregaEstado($entregaEstado)
    {
        $this->entregaEstado = $entregaEstado;
        return $this;
    }

    public function setRecogidaEstado($recogidaEstado)
    {
        $this->recogidaEstado = $recogidaEstado;
        return $this;
    }

    public function getPeticion()
    {
        return ($this->peticion);
    }

    public function getNotas()
    {
        return $this->notas;
    }

    public function setPeticion($peticion)
    {
        $this->peticion = $peticion;
    }

    public function setNotas($notas)
    {
        $this->notas = $notas;
    }

    public function getNumDias()
    {
        $interval = $this->fechaInicio->diff($this->fechaFin);
        return $interval->format('%a') + 1;
    }

    public function getTotalReceptores()
    {

src/AppBundle/Resources/views/Modulos/AccessosDirectos.twig
        <li><a href="{{app.request.getBaseUrl()}}/panel/listado/entregas"><i class="fa fa-circle-o text-green"></i> <span>Recogidas y entregas</span></a></li>
        <li><a href="{{app.request.getBaseUrl()}}/panel/calendario"><i class="fa fa-circle-o text-yellow"></i> <span>Calendario</span></a></li>
        <li><a href="{{app.request.getBaseUrl()}}/panel/reservas/alta"><i class="fa fa-circle-o text-aqua"></i> <span>Agregar Reserva</span></a></li>

src/AppBundle/Resources/views/Modulos/AlquileresChart.html.twig
<canvas id="alquileresChart" style="height: 180px;"></canvas>
    <script src="{{app.request.getBasePath()}}/assets/chartjs/Chart.min.js"></script>
{{dump(datos)}}
<script>

//-----------------------
//- MONTHLY SALES CHART -
//-----------------------

// Get context with jQuery - using jQuery's .get() method.
        var salesChartCanvas = $("#alquileresChart").get(0).getContext("2d");
// This will get the first returned node in the jQuery collection.
        var salesChart = new Chart(salesChartCanvas);

        var salesChartData = {
            labels: [
                {{dump(datos)}}
                {%for fecha, dato in datos %}
                                "{{fechaa}}",
                {% endfor %}
                ],
            datasets: [
                {
                    label: "Standard",
                    fillColor: "rgb(210, 214, 222)",
                    strokeColor: "rgb(210, 214, 222)",
                    pointColor: "rgb(210, 214, 222)",
                    pointStrokeColor: "#c1c7d1",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgb(220,220,220)",
                    data: [
                {%for fecha, dato in datos %}
                                {{dato.RG01|default("0")}},
                {% endfor %}
                    ]
                },
                {
                    label: "Bluethoot",
                    fillColor: "rgb(66, 255, 188)",
                    strokeColor: "rgb(210, 214, 222)",
                    pointColor: "rgb(210, 214, 222)",
                    pointStrokeColor: "#c1c7d1",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgb(220,220,220)",
                    data: [
                {%for fecha, dato in datos %}
                    {{dump(dato)}}
                                {{dato.SAU|default("0")}},
                {% endfor %}
                    ]
                }
                
            ]
        };
    $(function () {

        var salesChartOptions = {
//Boolean - If we should show the scale at all
            showScale: true,
//Boolean - Whether grid lines are shown across the chart
            scaleShowGridLines: false,
//String - Colour of the grid lines
            scaleGridLineColor: "rgba(0,0,0,.05)",
//Number - Width of the grid lines
            scaleGridLineWidth: 1,
//Boolean - Whether to show horizontal lines (except X axis)
            scaleShowHorizontalLines: true,
//Boolean - Whether to show vertical lines (except Y axis)
            scaleShowVerticalLines: true,
//Boolean - Whether the line is curved between points
            bezierCurve: true,
//Number - Tension of the bezier curve between points
            bezierCurveTension: 0.3,
//Boolean - Whether to show a dot for each point
            pointDot: false,
//Number - Radius of each point dot in pixels
            pointDotRadius: 4,
//Number - Pixel width of point dot stroke
            pointDotStrokeWidth: 1,
//Number - amount extra to add to the radius to cater for hit detection outside the drawn point
            pointHitDetectionRadius: 20,
//Boolean - Whether to show a stroke for datasets
            datasetStroke: true,
//Number - Pixel width of dataset stroke
            datasetStrokeWidth: 2,
//Boolean - Whether to fill the dataset with a color
            datasetFill: false,
//Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
            maintainAspectRatio: true,
//Boolean - whether to make the chart responsive to window resizing
            responsive: true,
            
            legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){ %><li><span style=\"background-color:<%=datasets[i].lineColor%>\"></span><%if(datasets[i].label){ %><%=datasets[i].label%><%}%></li><%}%></ul>",
        };

//Create the line chart
        salesChart.Line(salesChartData, salesChartOptions);

//---------------------------
//- END MONTHLY SALES CHART -
//---------------------------
    });

</script>

src/AppBundle/Resources/views/Modulos/Direccion.twig
{% if direccion is not null%}
    {{direccion}}<br>
    {{direccion.direccion}}<br>
    {{direccion.municipio}} {{direccion.provincia}}<br>
    {{direccion.cp}} {{direccion.pais}}<br>
{% else %}
    Sin definir
{% endif %}                                    

src/AppBundle/Resources/views/Modulos/Movimientos.html.twig
<table class="table table-condensed dataTable">
    <thead>
        <tr>
            <th style="width: 30px">ID</th>
            {% if tipo == 'recogida' %}
            <th>Recogida</th>
            <th class="hidden-xs">Fin</th>
            {% elseif tipo == 'entrega' %}
            <th>Entrega</th>
            <th class="hidden-xs">Inicio</th>            
            {% endif %}
{#            <th>Cliente</th>#}
            <th>Ubicación</th>
            <th>Ciudad</th>
            <th style="text-align:center">Uds.</th>
            <th style="text-align:center">Mod.</th>
            <th style="min-width: 100px;">Referencia</th>
            <th style="text-align:center">D</th>            
            <th style="text-align:center">Estado</th>
        </tr>
    </thead>
    <tbody>
        {% for movimiento in movimientos %}
                <tr>
                    <td><a href="{{ path("reserva_show",{'reserva':movimiento.reserva.id}) }}" style="color:{{movimiento.estado.color | default("")}};">{{movimiento.reserva.id}}</a></td>
                    <td data-order="{{movimiento.fecha.timestamp}}"><b>{{movimiento.fecha.format("d-m")}}</b><br/>{{movimiento.fecha.format("H:i")}}</td>
                    {% if tipo == 'recogida' %}
                        <td data-order="{{movimiento.reserva.fechaFin.timestamp}}" class="hidden-xs">{{movimiento.reserva.fechaFin.format("d-m")}}<br />{{movimiento.reserva.fechaFin.format("H:i")}}</td>
                    {% elseif tipo == 'entrega' %}
                    <td data-order="{{movimiento.reserva.fechaInicio.timestamp}}" class="hidden-xs">{{movimiento.reserva.fechaInicio.format("d-m")}}<br />{{movimiento.reserva.fechaInicio.format("H:i")}}</td>
                    {% endif %}
{#                    <td>{{movimiento.reserva.empresa}}</td>#}
                    <td>{{movimiento.direccion.nombre | default(reserva.entregaDireccion.direccion | default(""))}}</td>
                    <td>{{movimiento.direccion.municipio | default("") }}</td>
                    <td style="text-align:center">{{movimiento.reserva.cantidadReceptores | default("0")}}</td>
                    <td style="text-align:center">{{movimiento.reserva.modelo | default("n/a")}}</td>
                    <td class="hidden-xs">{{movimiento.reserva.circuito | default("n/a")}}</td>
                    <td style="text-align:center" data-order="{{movimiento.restoDias}}"><span class="badge" style="background-color:{{movimiento.estado.color | default("")}}">{{movimiento.restoDias}}</span></td>                                        
                    {% if movimiento.estado.nombre == 'EN PREPARACION'  %}

                        <td style="text-align:center"><span class="badge estado" style="color:{{movimiento.estado.color | default("")}}; border-color: {{movimiento.estado.color | default("")}};" data-toggle="" title="En Preparación">{{"EP" | default("")}}</span></td>
                    {% elseif  movimiento.estado.nombre == 'SIN RECOGER'  %}
                        <td style="text-align:center"><span class="badge estado" style="color:{{movimiento.estado.color | default("")}}; border-color: {{movimiento.estado.color | default("")}};" data-toggle="" title="SIN RECOGER">{{"SR"| default("")}}</span></td>
                    {% elseif movimiento.estado.nombre == 'PREPARADO' %}
                        <td style="text-align:center"><span class="badge estado" style="color:{{movimiento.estado.color | default("")}}; border-color: {{movimiento.estado.color | default("")}};" data-toggle="" title="Reparado">{{"R"| default("")}}</span></td>
                    {% elseif movimiento.estado.nombre == 'ENVIADO' %}
                        <td style="text-align:center"><span class="badge estado" style="color:{{movimiento.estado.color | default("")}}; border-color: {{movimiento.estado.color | default("")}};" data-toggle="" title="Enviado">{{"E"| default("")}}</span></td>   
                    {% elseif movimiento.estado.nombre == 'INCIDENCIA' %}
                        <td style="text-align:center"><span class="badge estado" style="color:{{movimiento.estado.color | default("")}}; border-color: {{movimiento.estado.color | default("")}};" data-toggle="" title="Incidencia">{{"I"| default("")}}</span></td>   
                    {% elseif movimiento.estado.nombre == 'FINALIZADO' %}
                           <td style="text-align:center"><span class="badge estado" style="color:{{movimiento.estado.color | default("")}}; border-color: {{movimiento.estado.color | default("")}};" data-toggle="" title="Finalizado">{{"F"| default("")}}</span></td>   
                    {% endif %} 
                    
                </tr>
        {% endfor %}
    </tbody>
</table>

src/AppBundle/Resources/views/Modulos/Reservas.html.twig
{% if filtro is defined and filtro is not null %}
<form action="" />
<table class="table table-condensed">
    <tr>
        <td>Filtros:</td>
        <td><input type="date" name="inicio" value="{{filtro.valores.inicio | default("01-01-2017")}}"/></td>
        <td><input type="date" name="fin" value="{{filtro.valores.fin | default("31-12-2017")}}"/></td>
            <td><select name="estado">
                <option value="">Estado - Todos</option>
                {% for estado in filtro.opciones.estados %}
                    <option value="{{estado.id}}" {% if filtro.valores.estado == estado %}selected="selected"{% endif %}>{{estado}}</option>
                {% endfor %}
            </select></td>
            <td><select name="cliente" class="select2">
                <option value="">Cliente - Todos</option>
                {% for cliente in filtro.opciones.clientes %}
                    <option value="{{cliente.id}}" {% if filtro.valores.cliente == cliente.id %}selected="selected"{% endif %}>{{cliente}}</option>
                {% endfor %}
            </select></td>
            <td><select name="modelo">
                <option value="">Modelo - Todos</option>
                <option value="RG01" {% if filtro.valores.modelo == "RG01" %}selected="selected"{% endif %}>RG01</option>
                <option value="SAU" {% if filtro.valores.modelo == "SAU" %}selected="selected"{% endif %}>SAU</option>
            </select></td>
        <td><input type="checkbox" name="lduracion"{% if filtro.valores.lduracion == 'on' %}checked="checked"{% endif %}/>Larga Duración</td>
        <td><input type="submit" class="boton" value="Filtrar" />
    </tr>
</table>
</form>
{% endif %}

<table id="tb_reservas" class="table table-condensed dataTable">
    <thead>
        <tr>
            <th style="width: 30px">ID</th>
            <th>Inicio</th>
            <th>Fin</th>
            <th class="hidden-xs">D.</th>
            <th>Cliente</th>
            <th class="hidden-xs">Referencia</th>
            <th style="text-align:center">Uds.</th>
            {% if tipo is not defined or tipo != "cliente" %}
                <th style="text-align:center">Modelo</th>
            {% endif %}
            <th style="text-align:center">Estado</th>
            <th style="text-align:center">Entrega</th>
            <th style="text-align:center">Recogida</th>
            <th style="text-align:right">Total</th>
        </tr>
    </thead>
    <tbody>
        {% for reserva in reservas %}
            <tr  style="page-break-inside: avoid;">
                <td><a href="{{ path('reserva_show' ,{'reserva':reserva.id})}}" style="color: {{reserva.estado.color | default("")}};">{{reserva.id}}</a></td>
                <td data-order="{{reserva.fechaInicio.timestamp}}">{{reserva.fechaInicio.format("d-m-y")}}</td>
                <td data-order="{{reserva.fechaFin.timestamp}}">{{reserva.fechaFin.format("d-m-y")}}</td>                
                <td class="hidden-xs">{{reserva.numDias}}</td>
                <td>{{reserva.empresa.nombre | default("")}}</td>
                <td class="hidden-xs">{{reserva.circuito | default("")}}</td>
                <td style="text-align:center">{{reserva.cantidadReceptores | default("0")}}</td>
                {% if tipo is not defined or tipo != "cliente" %}
                <td style="text-align:center">{{reserva.modelo | default("")}}</td>
                {% endif %}
                <td style="text-align:center"><span class="badge estado" style="color: {{reserva.estado.color | default("")}};border-color: {{reserva.estado.color | default("")}};">{{reserva.estado.nombre | default("")}}</span></td>
                <td style="text-align:center"><span class="badge estado" style="color: {{reserva.entrega.estado.color | default("red")}};border-color: {{reserva.entrega.estado.color | default("red")}};">{% if tipo is not defined or tipo != "cliente" %}{{reserva.entrega.fecha.format("d-m H:i") | default("s/a")}}{% else %}{{reserva.entrega.fecha.format("d-m") | default("s/a")}}{% endif %}</span></td>
                <td style="text-align:center"><span class="badge estado" style="color: {{reserva.recogida.estado.color | default("red")}};border-color: {{reserva.recogida.estado.color | default("red")}};">{% if tipo is not defined or tipo != "cliente" %}{{reserva.recogida.fecha.format("d-m H:i") | default("s/a")}}{% else %}{{reserva.recogida.fecha.format("d-m") | default("s/a")}}{% endif %}</span></td>                
                <td style="text-align:right" data-order="{{reserva.total}}">{{reserva.total|number_format(2, '.', ',')}} €</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
        

src/AppBundle/Resources/views/Modulos/print-menu.html.twig
<div class="dropdown-menu multi-column dropdown-add">
    <div class="container-fluid">
        <div class="row">

            <ul class="dropdown-menu">
                <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="/panel/pdf" target="_blank">Panel</a>
                </li>
                <li role="presentation">
                    <a role="menuitem" tabindex="-1" href="/panel/movimientos/pendientespdf" target="_blank">Recogidas y entregas</a>
                </li>
            </ul>
        </div>
    </div>

</div>