src/Iweb/FactuBundle/Entity/Factura.php
<?php

namespace Iweb\FactuBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Factura
 *
 * @ORM\Table(name="factura")
 * @ORM\Entity(repositoryClass="Iweb\FactuBundle\Repository\FacturaRepository")
 * @ORM\HasLifecycleCallbacks()

 */
class Factura
{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="numero", type="integer")
     */
    private $numero;

    /**
     * @var datetime
     *
     * @ORM\Column(name="fecha_creacion", type="datetime")
     */
    private $fechaCreacion;

    /**
     * @var datetime
     *
     * @ORM\Column(name="fecha_emision", type="datetime")
     */
    private $fechaEmision;

    /**
     * @var Estado
     *
     * @ORM\ManyToOne(targetEntity="Estado")
     * @ORM\JoinColumn(name="estadoId", referencedColumnName="id")
     */
    private $estado;

    /**
     * @var int
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Reserva", mappedBy="factura")
     *
     */
    private $pedido;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Empresa")
     */
    private $emisor;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Empresa")
     */
    private $receptor;

    public function __construct()
    {
        $this->fechaCreacion = new \DateTime();
        $this->fechaEmision = new \DateTime();
        $this->pedido = new \Doctrine\Common\Collections\ArrayCollection();
    }

//    /**
//    * @ORM\PrePersist
//    * @ORM\PreUpdate
//    */
//    public function prePersist(){
//        if($this->id == null){
//            $ultima = $this->get('facturacion.factura')->ultimo();
//            $this->numero = $ultima+1;
//        }
//    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    function getFechaCreacion()
    {
        return $this->fechaCreacion;
    }

    function getFechaEmision()
    {
        return $this->fechaEmision;
    }

    function getEstado()
    {
        return $this->estado;
    }

    function getEmisor()
    {
        return $this->emisor;
    }

    function getReceptor()
    {
        return $this->receptor;
    }

    /**
     *
     * @return \AppBundle\Entity\Reserva[]
     */
    function getPedido()
    {
        return $this->pedido;
    }

    function setFechaCreacion($fechaCreacion)
    {
        $this->fechaCreacion = \DateTime::createFromFormat("Y-m-d", $fechaCreacion);
        return $this;
    }

    function setFechaEmision($fechaEmision)
    {
        $this->fechaEmision = \DateTime::createFromFormat("Y-m-d", $fechaEmision);
        return $this;
    }

    function setEstado($estado)
    {
        $this->estado = $estado;
        return $this;
    }

    function setEmisor($emisor)
    {
        $this->emisor = $emisor;
        return $this;
    }

    function setNumero($numero)
    {
        $this->numero = $numero;
        return $this;
    }

    function setReceptor($receptor)
    {
        $this->receptor = $receptor;
        return $this;
    }

    public function getNumero()
    {
        return $this->numero;
    }

    function addPedido(\AppBundle\Entity\Reserva $pedido)
    {
        $this->pedido[] = $pedido;
        return $this;
    }

    function getTotal()
    {
        $subtotal = 0;
        foreach ($this->pedido as $pedido) {
            $subtotal += $pedido->getTotal();
        }
        return $subtotal;
    }

    function getTotalBruto()
    {
        $subtotal = 0;
        foreach ($this->pedido as $pedido) {
            $subtotal += $pedido->getTotalBruto();
        }
        return $subtotal;
    }

    function getImpuestos()
    {
        return $this->pedido[0]->getPrecioImpuestos();
    }

    public function getTotalImpuestos()
    {
        return $this->getTotal() - $this->getTotalBruto();
    }

}

src/Iweb/FactuBundle/Controller/DefaultController.php
<?php

namespace Iweb\FactuBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Factura controller.
 *
 * @Route("/facturacion")
 */
class DefaultController extends Controller
{

    /**
     * @Route("/", name="facturacion_index")
     */
    public function indexAction(Request $request)
    {
        //$facturas = $Empresa = $this->getDoctrine()->getRepository('IwebFactuBundle:Factura')->findAll();
        $trimestre = $request->query->get('trimestre');
        $ano = $request->query->get('ano');
        $cliente = $request->query->get('cliente');
        $queryBuilder = $this->getDoctrine()->getManager()->createQueryBuilder();
        $query = $queryBuilder
                ->select('f')
                ->from('IwebFactuBundle:Factura', 'f');

        if (!$this->isGranted('ROLE_RG_GLOBAL')) {
            $query->where("f.receptor = :empresa");
            if ($this->isGranted('ROLE_RG_FINANCIERO')) {
                $query->where("f.emisor = :empresa");
            }
            $query->setParameter("empresa", $this->getUser()->getEmpresa());
        }

        if (!is_null($ano) && strlen($ano) == 4) {
            switch ($trimestre) {
                case '1T':
                    $fini = \DateTime::createFromFormat("d-m-Y", "00-01-" . $ano);
                    $ffin = \DateTime::createFromFormat("d-m-Y", "31-03-" . $ano);
                    break;
                case '2T':
                    $fini = \DateTime::createFromFormat("d-m-Y", "00-04-" . $ano);
                    $ffin = \DateTime::createFromFormat("d-m-Y", "30-06-" . $ano);
                    break;
                case '3T':
                    $fini = \DateTime::createFromFormat("d-m-Y", "00-07-" . $ano);
                    $ffin = \DateTime::createFromFormat("d-m-Y", "30-09-" . $ano);
                    break;
                case '4T':
                    $fini = \DateTime::createFromFormat("d-m-Y", "00-10-" . $ano);
                    $ffin = \DateTime::createFromFormat("d-m-Y", "31-12-" . $ano);
                    break;
                default:
                    $fini = \DateTime::createFromFormat("d-m-Y", "00-01-" . $ano);
                    $ffin = \DateTime::createFromFormat("d-m-Y", "31-12-" . $ano);
                    break;
            }
            $query->andwhere('f.fechaEmision >= :fini AND f.fechaEmision <= :ffin');
            $query->setParameter("fini", $fini)
                    ->setParameter("ffin", $ffin);
        }
        if ($cliente != null) {
            $cliente = $this->getDoctrine()->getRepository('AppBundle:Empresa')->findOneById($cliente);
            if (!is_null($cliente)) {
                $query->andwhere('f.receptor = :cliente')
                        ->setParameter(":cliente", $cliente);
            }
        }
        $facturas = $query->getQuery()->getResult();

        $empresas = $this->getDoctrine()->getRepository('AppBundle:Empresa')->findAll();

        return $this->render('IwebFactuBundle:Default:index.html.twig', array('facturas' => $facturas, 'empresas' => $empresas, "filtro" => array(
                        "ano" => $ano,
                        "trimestre" => $trimestre,
                        "empresa" => $cliente
                    ))
        );
    }

    /**
     * @Route("/new", name="facturacion_new")
     * @Route("/new/{idcliente}/{idreserva}", name="facturacion_new_simple")
     */
    public function newAction(Request $request, $idcliente = null, $idreserva = null)
    {
        //Obtenermos las reservas pedientes de facturar.
        $reservas = $request->request->get('reservas');
        $fecha = $request->request->get('fecha');

        if (is_null($idreserva) && !is_null($reservas)) {
            foreach ($reservas as $idcliente => $reservascli) {
                $this->generarFactura($idcliente, $reservascli, $fecha);
            }
            return $this->redirectToRoute('facturacion_index');
        }

        if (is_null($idreserva) && is_null($reservas)) {
            $queryBuilder = $this->getDoctrine()->getManager()->createQueryBuilder();
            /* @var $queryBuilder \Doctrine\ORM\QueryBuilder */
            $query = $queryBuilder
                    ->select('r')
                    ->from(\AppBundle\Entity\Reserva::class, 'r')
                    ->where("r.factura is NULL ")
                    ->join("r.estado", "e")
                    ->andWhere("e.activa = 1 OR e.nombre = 'FINALIZADA' ")
//                    ->setParameter(":act", true)
//                    ->setParameter(":efin", "FINALIZADA")
                    ->orderBy("r.id")
                    ->orderBy("r.empresa")
            ;

            $activas = $query->getQuery()->getResult();
            return $this->render('IwebFactuBundle:Default:new.html.twig', array("activas" => $activas));
        }

        if (!is_null($idreserva)) {
            $idfactura = $this->generarFactura($idcliente, array($idreserva), $fecha);
            return $this->redirectToRoute('factura_print', array('id' => $idfactura));
        }

        return $this->redirectToRoute('facturacion_index');
    }

    public function generarFactura($idcliente, $pedidos, $fecha = null)
    {
        $Empresa = $this->getDoctrine()->getRepository(\AppBundle\Entity\Empresa::class)->find($idcliente);
        if (!$Empresa) {
            throw $this->createNotFoundException('Empresa no encontrada con el ID ' . $idcliente);
        }
        if (is_null($fecha)) {
            $fecha = date("Y-m-d");
        }
        $EmprePropia = $this->getDoctrine()->getRepository(\AppBundle\Entity\Empresa::class)->findOneByNombre("RG Spain");
        $Factura = new \Iweb\FactuBundle\Entity\Factura();
        $Factura->setEmisor($EmprePropia);
        $Factura->setReceptor($Empresa);
        $Factura->setFechaEmision($fecha);
        $em = $this->getDoctrine()->getManager();
        foreach ($pedidos as $idreserva) {
            /* @var $Reserva \AppBundle\Entity\Reserva */
            $Reserva = $em->getRepository(\AppBundle\Entity\Reserva::class)->find($idreserva);
            if (!$Reserva) {
                throw $this->createNotFoundException('Reserva no encontrada con el ID ' . $idreserva);
            }
            if ($Reserva->getFactura() !== null) {
                throw $this->createNotFoundException('Reserva ya facturada ' . $idreserva . ' - Factura:' . $Reserva->getFactura());
            }
            if ($Reserva->getEntrega()->getEstado()->getNombre() == "FINALIZADO" && $Reserva->getRecogida()->getEstado()->getNombre() == "FINALIZADO") {
                $erFinalizada = $em->getRepository(\AppBundle\Entity\Estado\Reserva::class)->findOneByNombre("FINALIZADA");
                $Reserva->setEstado($erFinalizada);
            }
            $Reserva->setFactura($Factura);
            $Factura->addPedido($Reserva);
            $em->persist($Reserva);
        }
        $ef_facturada = $em->getRepository(\Iweb\FactuBundle\Entity\Estado::class)->findOneByNombre("FACTURADA");
        $Factura->setEstado($ef_facturada);
        $ultima = $this->get('facturacion.factura')->ultima(\DateTime::createFromFormat("Y-m-d", $fecha)->format("Y"));
        $Factura->setNumero(($ultima));
        $em->persist($Factura);
        $em->flush();
        return $Factura->getId();
    }

}

src/Iweb/FactuBundle/Resources/views/Default/index.html.twig
{% extends "@App/panel.html.twig" %}

{% block main %}
    <div class="box box-azul box-solid">
        <div class="box-header">
            <h3 class="box-title">Facturas Emitidas</h3>
            <div class="box-tools pull-right">
                <span data-toggle="tooltip" title="" class="badge" data-original-title="3 Entregas pendientes" style="font-size: 1.2em">{{facturas| length}}</span>
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-condensed dataTable">
                <thead>
                    <tr>
                        <th>Nº</th>
                        <th>Fecha</th>
                        <th>CIF</th>
                        <th>Pais</th>
                        <th>Cliente</th>
                        <th>Reservas</th>
                        <th>Base</th>
                        <th>Imp.</th>
                        <th>Impuestos</th>
                        <th>Total</th>
                        <th>Estado</th>
                        <th>Imprimir</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                {% set facturastotalBruto = 0 %}
                {% set facturastotal = 0 %}
                {% set facturasImpuestos = 0 %}
                <tbody>
                    {% for factura in facturas %}
                        <tr>
                            <td>{{factura.fechaEmision.format('Y')}}{{"%03d"|format(factura.numero)}}</td>
                            <td data-order="{{factura.fechaEmision.format('U')}}">{{factura.fechaEmision.format('d-m-Y')}}</td>
                            <td>{{factura.receptor.cif | default("")}}</td>
                            <td>{{factura.receptor.dirFacturacion.pais | default("")}}</td>
                            <td>{{factura.receptor.sociedad | default("")}}</td>
                            <td>
                                {% for reserva in factura.pedido %}
                                    <a href="{{ path("reserva_show",{"reserva":reserva.id}) }}">{{reserva.id}}</a>
                                    {% if loop.last == false %}
                                        &nbsp;|&nbsp;
                                    {% endif %}
                                {% endfor %}
                            </td>

                            {% if factura.estado.nombre != "REEMBOLSO" %}
                                <td>{{factura.totalBruto|number_format(2, '.', ',')}} €</td>
                                <td>{{factura.impuestos|number_format(0)}}%</td>
                                <td>{{factura.totalImpuestos|number_format(2, '.', ',')}} €</td>
                                <td>{{factura.total|number_format(2, '.', ',')}} €</td>
                                {% set facturastotalBruto = facturastotalBruto + factura.totalBruto %}
                                {% set facturastotal = facturastotal + factura.total %}
                                {% set facturasImpuestos = facturasImpuestos + factura.totalImpuestos %}
                            {% else %}
                                <td><del>{{factura.totalBruto|number_format(2, '.', ',')}} €</del></td>
                                <td><del>{{factura.impuestos|number_format(0)}}%</del></td>
                                <td><del>{{factura.totalImpuestos|number_format(2, '.', ',')}} €</del></td>
                                <td><del>{{factura.total|number_format(2, '.', ',')}} €</del></td>
                            {% endif %}
                            <td>{{factura.estado.nombre}}</td>
                            <td><a target="_blank" href="{{ path('factura_print', {'id': factura.id}) }}">Imprimir</a></td>
                            <td>
                                {% if factura.estado.nombre == "FACTURADA" %}
                                    <a href="{{ path('factura_estado', {'id': factura.id}) }}">Cobrar</a> |
                                    <a class="borrarFactura" href="{{ path('factura_borrar', {'id': factura.id}) }}">Borrar</a>
                                {% elseif factura.estado.nombre == "PAGADA" %}
                                    <a href="{{ path('factura_estado', {'id': factura.id}) }}">Reembolso</a>
                                {% elseif factura.estado.nombre == "REEMBOLSO" %}
                                    <a href="{{ path('factura_estado', {'id': factura.id}) }}">Pte. Cobro</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="8" style="text-align: center">No existen facturas disponibles</td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th>Totales</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>

                    </tr>
                </tfoot>

            </table>
        </div>
        <div class="box-footer">
            <form method="GET" action="{{ path("facturacion_index") }}" >
                <table class="table table-condensed">
                    <tr>
                        <td>Filtros:</td>
                        <td>
                            <select name="trimestre">
                                <option value="">Todos</option>
                                <option value="1T"{% if filtro.trimestre == "1T" %}selected="selected"{% endif %}>1T</option>
                                <option value="2T"{% if filtro.trimestre == "2T" %}selected="selected"{% endif %}>2T</option>
                                <option value="3T"{% if filtro.trimestre == "3T" %}selected="selected"{% endif %}>3T</option>
                                <option value="4T"{% if filtro.trimestre == "4T" %}selected="selected"{% endif %}>4T</option>
                            </select>
                        </td>
                        <td>
                            <select name="ano">
                                <option value="">Todos</option>
                                <option value="2016"{% if filtro.ano == "2016" %}selected="selected"{% endif %}>2016</option>
                                <option value="2017"{% if filtro.ano == "2017" %}selected="selected"{% endif %}>2017</option>
                                <option value="2018"{% if filtro.ano == "2018" %}selected="selected"{% endif %}>2018</option>
                            </select>
                        </td>
                        <td>
                            <select name="cliente" class="select2">
                                <option value="">Todos</option>
                                {% for empresa in empresas %}
                                    <option value="{{empresa.id}}"{% if filtro.empresa.id|default(null) == empresa.id %}selected="selected"{% endif %}>{{empresa}}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td>
                            <input type="submit" value="Filtrar" class="boton"/>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <!-- /.box-body -->
    </div>
    {#    {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Create" />
    {{ form_end(form) }}
#}
    {#    <ul>
            <li>
                <a href="{{ path('factura_index') }}">Back to the list</a>
            </li>
        </ul>
    #}{% endblock main %}

{% block javascripts %}
    {{parent()}}
    <script>
        $(function () {
            $('.dataTable').DataTable({
                "paging": true,
                "bPaginate": false,{#                "lengthChange": false,#}
        {#                "searching": false,#}
                    "ordering": true,
                    "order": [[0, 'desc']],
        {#                "info": false,#}
                    "autoWidth": false,
        {#                drawCallback: function () {
                          var api = this.api();
                          $( api.table().footer() ).html(
                            api.column( 7, {page:'current'} ).data().sum()
                          );
                        }
        #}
                    "footerCallback": function (row, data, start, end, display) {
                        var api = this.api(), data;

                        base_total = api.column(6).data().sum();
                        base_page = api.column(6, {page: 'current'}).data().sum();
                        $(api.column(6).footer()).html(base_page + '€<br/>' + base_total + '€');

                        imp_total = api.column(8).data().sum();
                        imp_page = api.column(8, {page: 'current'}).data().sum();
                        $(api.column(8).footer()).html(imp_page + '€<br/>' + imp_total + '€');

                        total = api.column(9).data().sum();
                        page = api.column(9, {page: 'current'}).data().sum();
                        $(api.column(9).footer()).html(page + '€<br/>' + total + '€');
                    }

                });
                $('.borrarFactura').on('click', function (e) {
                    e.preventDefault();
                    $.confirm({
                        title: 'Borrar factura?',
                        content: '{{app.user }} estás seguro que quieres borrar esta factura?.',
                        autoClose: 'cancelar|8000',
                        buttons: {
                            deleteUser: {
                                text: 'Borrar',
                                action: function () {
                                    window.location.href = $('#borrarReserva').attr('href');
                                }
                            },
                            cancelar: function () {
                                $.alert('Uff, por los pelos..');
                            }
                        }
                    });
                });

            });
    </script>
{% endblock javascripts %}